// <auto-generated />
using System;
using ArtService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtService.Persistence.Migrations
{
    [DbContext(typeof(ArtServiceDbContext))]
    [Migration("20250512184819_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtService.Domain.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("VolumeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId", "Order");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("ArtService.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParagraphId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpoilerChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphId");

                    b.HasIndex("SpoilerChapterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ArtService.Domain.LiteraryArchetype", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NarrativeType")
                        .HasColumnType("integer");

                    b.Property<int>("PurposeType")
                        .HasColumnType("integer");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<int>("ToneType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "NarrativeType", "ToneType", "PurposeType")
                        .IsUnique();

                    b.ToTable("LiteraryArchetypes");

                    b.HasData(
                        new
                        {
                            Id = "RBSI",
                            Name = "Судья",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "RBSE",
                            Name = "Хроникёр",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "RBLI",
                            Name = "Свидетель",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "RBLE",
                            Name = "Бард",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "RHSI",
                            Name = "Мудрец",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "RHSE",
                            Name = "Отшельник",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "RHLI",
                            Name = "Пилигрим",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "RHLE",
                            Name = "Арлекин",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "FBSI-P",
                            Name = "Пророк",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "FBSE",
                            Name = "Герой",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "FBLI",
                            Name = "Алхимик",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "FBLE",
                            Name = "Трикстер",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "FHSI",
                            Name = "Оракул",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "FHSE",
                            Name = "Мистик",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = "FHLI",
                            Name = "Визионер",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = "FHLE",
                            Name = "Чародей",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        });
                });

            modelBuilder.Entity("ArtService.Domain.LiteraryTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NarrativeType")
                        .HasColumnType("integer");

                    b.Property<int>("PurposeType")
                        .HasColumnType("integer");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<int>("ToneType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "NarrativeType", "ToneType", "PurposeType");

                    b.ToTable("LiteraryTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13955ae4-a8e9-497a-ad2c-2124999143ea"),
                            Name = "От первого лица",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("82764e64-6856-445d-81cf-6d5e8297a924"),
                            Name = "Ненадёжный рассказчик",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("efc99aab-4a12-495d-8a9b-764277170b7c"),
                            Name = "Письма",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("e53c081a-6f7c-42f5-a523-f2a90d41e6f8"),
                            Name = "Нелинейность",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("e45cd96e-a0f1-46c5-bc6d-3d83c9cba91c"),
                            Name = "Антигерой",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("33d416cf-48f2-4eaf-bd46-6f49647629f9"),
                            Name = "Моральный выбор",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("fb5e1492-48a1-4bd1-a9ff-a3629e2547e6"),
                            Name = "Рост героя",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("42158584-39a4-4018-a835-44a3be36dd52"),
                            Name = "Трагедия",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("a20d0390-9ef2-41b6-92cd-9e272f20b2c7"),
                            Name = "Внутренний конфликт",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("8064693a-cff3-4b4c-b604-ad8dcfa039b6"),
                            Name = "Наставник",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("4230c8d6-6776-46fb-9280-fcfcab67d194"),
                            Name = "Предательство",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("2dff17b0-0d10-44bb-9cc1-a0747dd3439f"),
                            Name = "Исторический сеттинг",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("8e64f15a-d184-423e-8fa1-451eb69039ab"),
                            Name = "Футуризм",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("6dd0fcc1-b72d-4c64-9fc0-20f2b68a73e0"),
                            Name = "Дистопия",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("45e8b8e3-0ca3-4f4b-a2d0-64d4f06f11a7"),
                            Name = "Утопия",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("2dc5ab6b-6f43-4eed-9edd-5bac31a52d17"),
                            Name = "Система магии",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("395299ea-8bab-4785-9e06-cd19f7878d87"),
                            Name = "Инопланетная цивилизация",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("66ed4746-bd03-44d4-a1ee-3aa69733198c"),
                            Name = "Альтернативная реальность",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("bea81375-c96d-47e5-a85c-928c5ce114d6"),
                            Name = "Природа",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("c82852fd-6ddb-4bb0-98a8-e0e67fe17ecf"),
                            Name = "Городская среда",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("9bdf3b1a-108a-4be3-b129-c8ad66e9d05b"),
                            Name = "Постапокалипсис",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("d1589788-f740-4920-9c1d-8216309f9927"),
                            Name = "Политика",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("697ce266-b023-41fa-a25d-9c72863d8efa"),
                            Name = "Общество",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("7aafcbcc-fd38-4044-abb5-d45b2ed7b320"),
                            Name = "Поиск смысла",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("ef404207-a797-4ba5-8943-a0be3211366b"),
                            Name = "Любовь",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("ce0476b5-1a1b-4215-90c7-cbd0e1309450"),
                            Name = "Смерть",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("daecf81a-4b2b-45b8-ae3c-9b817e14eb41"),
                            Name = "Свобода",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("7dbe2c49-3100-4581-b08f-70b0c22565ad"),
                            Name = "Человеческая природа",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("5a06d6b9-c24e-4f41-ad79-bcef46693816"),
                            Name = "Отчуждение",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("224649db-9083-4e76-8a10-145afd78efdd"),
                            Name = "Интрига",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("eeff65f7-c613-4fae-ae96-122c05462bc8"),
                            Name = "Эмоции",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("0614effc-9be3-4632-af7c-70cd487fd86c"),
                            Name = "Трагизм",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("aa5b9c59-383d-4a22-86cf-92289cee9c57"),
                            Name = "Юмор",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("4836389e-2c76-4862-a27f-3177eb7df4d1"),
                            Name = "Страх",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("a8147c76-a2e2-4af1-9361-ede3d20d646b"),
                            Name = "Ностальгия",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("6b940f12-a125-4a63-a0b8-cb5e9b317bac"),
                            Name = "Надежда",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("7d71c4b3-18c7-4e02-b110-2fab2a1a9536"),
                            Name = "Философия",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("13d4d535-3df2-4eb1-8804-59e8ea0c31c6"),
                            Name = "Критика",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("9315dd35-30af-4ca8-9411-1d3d54860f36"),
                            Name = "Обучение",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("45f1b833-8005-4538-b4a2-4448430e9707"),
                            Name = "Эскапизм",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("dd971aa7-7153-4cf2-836a-3e9e473c536b"),
                            Name = "Аллегория",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("967ef310-6c90-4e63-92b0-ac1a507b8ef9"),
                            Name = "Символизм",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("de8bef6b-8d5e-4495-a8d2-7eedcd3551fe"),
                            Name = "Сатира",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("f4114e01-837e-4228-9a6b-2cbeab19f5ea"),
                            Name = "Минимализм",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("63eaa89b-d59a-4171-907a-77f092129910"),
                            Name = "Архаизм",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("16277759-6195-4c8d-a40f-def5623cd90b"),
                            Name = "Рефлексия",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("f70f2d76-0cc9-4b79-9d31-c23086aa515a"),
                            Name = "Интерактивность",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("03a5f83c-7187-41b3-9cc3-db11210733d3"),
                            Name = "Метастиль",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("ab9e3345-7d5e-43b4-a214-3ed0d6cf094a"),
                            Name = "Обращение",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("b5ed9540-25a7-4847-81a3-a16ae018163e"),
                            Name = "Открытый финал",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("0cb3ee49-f561-4237-af0d-7d2593bf2e00"),
                            Name = "Вызов нормам",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("ffe13f34-dc99-45ee-9292-ba36f36bbe57"),
                            Name = "Приключения",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("6326a2ad-168a-4dbf-9807-0780071bf9ce"),
                            Name = "Романтика",
                            NarrativeType = 0,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("8ef681b3-947d-444f-bf7f-477a15fa1ecf"),
                            Name = "Детектив",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("d0d6bd7b-474d-4c35-863a-b4fbb5290d77"),
                            Name = "Добро и зло",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("30f17aeb-8970-4631-9c63-1f29c1b39f78"),
                            Name = "Поколения",
                            NarrativeType = 1,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("ea62ce55-fe25-4993-a18b-05153b11693b"),
                            Name = "Судьба",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("8aea65ee-0997-4c1c-aa88-5f659b5843e3"),
                            Name = "Спасение мира",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("279a76fc-7733-4a43-80f4-6a06b418a9f2"),
                            Name = "Родственные связи",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("ebd6005f-42ef-43c6-8159-d1cc7b80d1a2"),
                            Name = "Бегство",
                            NarrativeType = 1,
                            PurposeType = 0,
                            ScopeType = 1,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("b4a16f13-f28b-4e43-bbd6-d241217b9455"),
                            Name = "Психология",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("88f023a5-3d83-45d1-a4fa-b7188ce81a6d"),
                            Name = "Страхи",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("98f20020-ebb7-40f2-876d-8983484a52e5"),
                            Name = "Желания",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("8daec224-778f-41d8-a04b-77934e644d6d"),
                            Name = "Самооценка",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("a104f842-dcd0-4f22-8a73-fc07802f1275"),
                            Name = "Тревожность",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("8bbcf0a6-841c-488b-96d5-4b66fcf95446"),
                            Name = "Осознание",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("ffda949c-bcb4-4668-9bc8-b0f92af5310c"),
                            Name = "Изменения",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        },
                        new
                        {
                            Id = new Guid("ac901868-ec5c-415c-8fb2-25e2086c7f51"),
                            Name = "Память",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("2dd3bcee-e678-4ff1-b7bd-38b45bf8b5a7"),
                            Name = "Одиночество",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 0
                        },
                        new
                        {
                            Id = new Guid("a24432ff-5627-4252-87c6-06ca19badcf7"),
                            Name = "Семья",
                            NarrativeType = 0,
                            PurposeType = 1,
                            ScopeType = 0,
                            ToneType = 1
                        });
                });

            modelBuilder.Entity("ArtService.Domain.Paragraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Order");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("ArtService.Domain.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParagraphId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("ArtService.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ArtService.Domain.Volume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverKey")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Order");

                    b.ToTable("Volumes");
                });

            modelBuilder.Entity("ArtService.Domain.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFanfic")
                        .HasColumnType("boolean");

                    b.Property<string>("LiteraryArchetypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalWorkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LiteraryArchetypeId");

                    b.HasIndex("OriginalWorkId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("LiteraryTagWork", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorksId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "WorksId");

                    b.HasIndex("WorksId");

                    b.ToTable("LiteraryTagWork");
                });

            modelBuilder.Entity("ArtService.Domain.Chapter", b =>
                {
                    b.HasOne("ArtService.Domain.Volume", "RelatedVolume")
                        .WithMany("Chapters")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedVolume");
                });

            modelBuilder.Entity("ArtService.Domain.Comment", b =>
                {
                    b.HasOne("ArtService.Domain.Paragraph", "RelatedParagraph")
                        .WithMany("Comments")
                        .HasForeignKey("ParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtService.Domain.Chapter", "SpoilerChapter")
                        .WithMany()
                        .HasForeignKey("SpoilerChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedParagraph");

                    b.Navigation("SpoilerChapter");
                });

            modelBuilder.Entity("ArtService.Domain.Paragraph", b =>
                {
                    b.HasOne("ArtService.Domain.Chapter", "RelatedChapter")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedChapter");
                });

            modelBuilder.Entity("ArtService.Domain.Reaction", b =>
                {
                    b.HasOne("ArtService.Domain.Paragraph", "RelatedParagraph")
                        .WithMany("Reactions")
                        .HasForeignKey("ParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedParagraph");
                });

            modelBuilder.Entity("ArtService.Domain.Review", b =>
                {
                    b.HasOne("ArtService.Domain.Work", "ReviewedWork")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedWork");
                });

            modelBuilder.Entity("ArtService.Domain.Volume", b =>
                {
                    b.HasOne("ArtService.Domain.Work", "RelatedWork")
                        .WithMany("Volumes")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedWork");
                });

            modelBuilder.Entity("ArtService.Domain.Work", b =>
                {
                    b.HasOne("ArtService.Domain.LiteraryArchetype", "LiteraryArchetype")
                        .WithMany("Works")
                        .HasForeignKey("LiteraryArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtService.Domain.Work", "OriginalWork")
                        .WithMany("Fanfics")
                        .HasForeignKey("OriginalWorkId");

                    b.Navigation("LiteraryArchetype");

                    b.Navigation("OriginalWork");
                });

            modelBuilder.Entity("LiteraryTagWork", b =>
                {
                    b.HasOne("ArtService.Domain.LiteraryTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtService.Domain.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtService.Domain.Chapter", b =>
                {
                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("ArtService.Domain.LiteraryArchetype", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("ArtService.Domain.Paragraph", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("ArtService.Domain.Volume", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("ArtService.Domain.Work", b =>
                {
                    b.Navigation("Fanfics");

                    b.Navigation("Reviews");

                    b.Navigation("Volumes");
                });
#pragma warning restore 612, 618
        }
    }
}
